### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by marcelloinfoweb** [smallshen/fleet_themes#1]
I insert into theme directory along with the other json files, rebooted Fleet and not uploaded to select.

**Comment by BlueStaggo** [comment]
I managed to use it by replacing dark_purple.json with the theme. Try that instead.

**Comment by marcelloinfoweb** [comment]
I found a directory in C:\Users\user\.fleet\themes I just put it on and it worked.

Thanks!

**Comment by smallshen** [comment]
@BlueStaggo make sure it's under <user_home>/.fleet/themes, not the themes under fleet install folder.
